### ISSUE TITLE
Paper and implementation are different.

### ISSUE THREAD

**Issue by jcwleo** [openai/large-scale-curiosity#6]
In paper, 
![image](https://user-images.githubusercontent.com/23333028/47658681-bae73900-dbd6-11e8-87b6-b9442948c2cb.png)
but, implementation just use reward. not sum of discounted reward.
Why is it different?

**Comment by yburda** [comment]
We are normalizing the reward here: https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/cppo_agent.py#L140
The normalization is by running std of a sum of discounted rewards here: https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/cppo_agent.py#L226-L236
One caveat is that for convenience we do the discounting backwards in time rather than forwards (it's convenient because at any moment the past is fully available and the future is yet to come).

**Comment by jcwleo** [comment]
@yburda thank you for reply. but i’ve already known that code. RewardFowrdFilter.rewems is None. so RewardForwardFilter.update just return input reward.
Am I thinking wrong?

**Comment by yburda** [comment]
Thank you for pointing this out. We will update the paper (we reported results with a version of code very similar to the published one, so the code is representative).

**Comment by jcwleo** [comment]
@yburda Did you mean that you did not use sum of dicounted reward?

**Comment by yburda** [comment]
Yes.

**Comment by jcwleo** [comment]
@yburda Thank you very much! :)

**Comment by yburda** [comment]
Upon thinking about it a bit longer - RewardForwardFilter.rewems is None only the first time you call update. Then it assigns something to it:
https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/cppo_agent.py#L233
And for all future calls to update, it's not None anymore.

Sorry for the temporary confusion.

**Comment by jcwleo** [comment]
Oh I was so stupid... Thank you for letting me know.

**Comment by alirezakazemipour** [comment]
> We are normalizing the reward here:
> 
> https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/cppo_agent.py#L140
> 
> The normalization is by running std of a sum of discounted rewards here:
> 
> https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/cppo_agent.py#L226-L236
> 
> One caveat is that for convenience we do the discounting backward in time rather than forwards (it's convenient because at any moment the past is fully available and the future is yet to come).

Sir, I think the code is not right;
It must have been `self.I.buf_rews_int.T[::-1]` as [**4kasha**](https://github.com/openai/random-network-distillation/issues/16#issuecomment-488387659) has mentioned.
and " _it's convenient because at any moment the past is fully available and the future is yet to come_" does not make sense, since you have collected **all the intrinsic rewards in a rollout**, so **the future is available**.
